routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\Moo2MeetingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

//AUTH GROUP
Route::group(['middleware' => ['auth']], function () {
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('meetings', Moo2MeetingController::class);
});

resources/views/partials/footer.blade.php
<div><a href="https://coreui.io">CoreUI </a><a href="https://coreui.io">Bootstrap Admin Template</a> &copy; 2021 creativeLabs.</div>
<div class="ms-auto">Powered by&nbsp;<a href="https://coreui.io/bootstrap/ui-components/">CoreUI UI Components</a></div>

resources/views/partials/form-status.blade.php
@if (session('message'))
    <div class="alert alert-{{ Session::get('status') }} status-box alert-dismissable fade show" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;<span class="sr-only">Close</span></a>
        {{ session('message') }}
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h4><i class="icon fa fa-check fa-fw" aria-hidden="true"></i> Success</h4>
        {{ session('success') }}
    </div>
@endif

@if(session()->has('status'))
    @if(session()->get('status') == 'wrong')
        <div class="alert alert-danger status-box alert-dismissable fade show" role="alert">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;<span class="sr-only">Close</span></a>
            {{ session('message') }}
        </div>
    @endif
@endif

@if (session('error'))
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h4>
            <i class="icon fa fa-warning fa-fw" aria-hidden="true"></i>
            Error
        </h4>
        {{ session('error') }}
    </div>
@endif

@if (session('errors') && count($errors) > 0)
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h4>
            <i class="icon fa fa-warning fa-fw" aria-hidden="true"></i>
            <strong>@lang('auth.whoops')</strong> @lang('auth.someProblems')
        </h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/partials/header.blade.php
<a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/home">eMeeting</a>
<button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="navbar-nav">
    <div class="nav-item text-nowrap">
{{--        <a class="nav-link px-3" href="#">Sign out</a>--}}
        @guest
            @if (Route::has('login'))
                    <a class="nav-link px-3" href="{{ route('login') }}">{{ __('Login') }}</a>

            @endif

            @if (Route::has('register'))
                    <a class="nav-link px-3" href="{{ route('register') }}">{{ __('Register') }}</a>

            @endif
        @else
{{--            <li class="nav-item dropdown">--}}
{{--                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>--}}
{{--                    {{ Auth::user()->name }}--}}
{{--                </a>--}}

{{--                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">--}}
                    <a class="nav-link px-3" href="{{ route('logout') }}"
                       onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
{{--                </div>--}}
{{--            </li>--}}
        @endguest
    </div>
</div>

resources/views/partials/sidebar.blade.php
<div class="position-sticky pt-3">
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>eMeeting Properties</span>
    </h6>
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{route('meetings.index')}}">
                <span data-feather="home"></span>
                Manage Meeting
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <span data-feather="file"></span>
                Orders
            </a>
        </li>
    </ul>

    @if(Auth::user()->hasRole('system admin'))
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Site Administrator</span>
        </h6>
        <ul class="nav flex-column mb-2">
            @if(Auth::user()->can('user-list'))
                <li class="nav-item">
                    <a class="nav-link" href="{{route('users.index')}}">
                        <span data-feather="file-text"></span>
                        Users
                    </a>
                </li>
            @endif
            @if(Auth::user()->can('role-list'))
                <li class="nav-item">
                    <a class="nav-link" href="{{route('roles.index')}}">
                        <span data-feather="file-text"></span>
                        Roles
                    </a>
                </li>
            @endif
            @if(Auth::user()->can('permission-list'))
                <li class="nav-item">
                    <a class="nav-link" href="{{route('permissions.index')}}">
                        <span data-feather="file-text"></span>
                        Permissions
                    </a>
                </li>
            @endif
        </ul>
    @endif
</div>