routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\Moo2MeetingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

//AUTH GROUP
Route::group(['middleware' => ['auth']], function () {
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('meetings', Moo2MeetingController::class);
});

resources/views/meetings/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <h5 class="card-header">
            <i class='fas fa-users-cog mr-2'></i> User Management
            @if(Auth::user()->can('user-create'))
                <div class="float-end">
                    <a class="btn btn-sm btn-success"
                       href="{{ route('users.create') }}"> New User</a>
                </div>
            @endif
        </h5>
        <div class="card-body">
            <div class="table-responsive">
            </div>
        </div>
    </div>
    {{--    @include('modals.modal-delete')--}}
@endsection
@section('third_party_stylesheets')
    <link rel="stylesheet" href="{{asset('/plugins/DataTables/DataTables-1.10.25/css/dataTables.bootstrap4.min.css')}}"/>
@stop
@section('third_party_scripts')
    {{--    @include('scripts.datatables')--}}
    {{--    @include('scripts.delete-modal-script')--}}
@stop